language: node_js
node_js:
  - "8.9.0"
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - npm run lint || travis_terminate 1
  - docker-compose -f devops/docker-compose.yml up -d || travis_terminate 1
  - npm run build:dev || travis_terminate 1
cache:
  directories:
    - ~/.npm
    - ~/.cache
